### ISSUE TITLE
1.2.1 define a number of key cities and stations around Switzerland and France

### ISSUE THREAD

**Issue by cgurtner** [cgurtner/PROG2-P05#1]
_Define a number of key cities and stations (ca. 50) around the borders of Switzerland and France across all directions._

Store 50 stations in a .csv file to lookup if the station is reachable from an address. If < 30 are reachable, define more until you have 30.

**Comment by fkapsahili** [comment]
- Create an automated script to fetch the main cities around the given countries (Switzerland and France)
- Store the city names in a dict
- It should be possible to automatically rebuild the dictionary of these cities and invalidate the cache

**Comment by cgurtner** [comment]
> * Create an automated script in the `script` folder to fetch the main cities and stations around the given countries (Switzerland and France) and store them as json in the `data` folder
> * It should be possible to automatically rebuild the dictionary of these cities and invalidate the cache
